version: '3.8'

services:
  # service_fetch_data:
  #   container_name: service_fetch_data
  #   build:
  #     context: "./service_fetch_data"
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - net

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    # platform: linux/arm64
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - net

networks:
  net:
    external: true
    driver: bridge

volumes:
  mysql_data:
